<?php
$translate = $this->plugin('translate');
?>
<nav class="f-pagination" role="navigation">
<?php if ($totalCount): ?>

    <?php if ($currentPage != 1): ?>
    <?php echo $this->hyperlink('', $previousPageUrl, ['class' => 'f-previous o-icon-prev button', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
    <?php else: ?>
    <span class="f-previous o-icon-prev f-button f-inactive"></span>
    <?php endif; ?>

    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
        Page <input type="text" name="page" class="f-page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'f-readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>"> <span class="f-page-count"><?php echo sprintf($translate('of %s'), $pageCount); ?></span>
    </form>

    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink('', $nextPageUrl, ['class' => 'f-next o-icon-next f-button', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
    <?php else: ?>
    <span class="f-next o-icon-next f-button f-inactive"></span>
    <?php endif; ?>

    <?php
    $from = $offset + 1;
    $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
    ?>
    <span class="f-row-count"><?php echo sprintf($translate('%1$s–%2$s of %3$s'), $from, $to, $totalCount); ?></span>
<?php else: ?>
    <?php echo $translate('0 results'); ?>
<?php endif; ?>
</nav>
