<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>

<dl>
<?php foreach ($values as $term => $propertyData): ?>
    <dt>
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="o-field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="o-field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
    </dt>
    <dd>
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $valueType = $value->type();
            $class = ['o-value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'o-resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'o-uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'o-private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="o-language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
        <?php endforeach; ?>
    </dd>
<?php endforeach; ?>
</dl>
