<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'o-item-set o-resource o-browse');
?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>

<div class="o-browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'o-advanced-search']); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="o-resource-list">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($itemSets as $itemSet):
    $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]) : $itemSet->displayTitle();
    $body = $bodyTerm ? $itemSet->value($bodyTerm) : $itemSet->displayDescription();
?>
    <li class="o-item-set o-resource hallo">
        <?php if($itemSetThumbnail = $this->thumbnail($itemSet, 'medium')): ?>
        <?php echo $itemSet->linkRaw($itemSetThumbnail); ?>
        <?php endif; ?>
        <h4><?php echo $itemSet->link($heading); ?></h4>
        <?php if ($body): ?>
        <div class="o-description"><?php echo $body; ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
