<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'o-item o-resource o-browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'o-item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<div class="f-grid-x f-grid-padding-x">

    <div class="f-cell f-small-12">

        <?php if ($itemSetShow): ?>
            <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
            <p class="t-lead"><?php echo $itemSet->value('dcterms:description'); ?></p>
            <div class="o-item-set-items">
        <?php else: ?>
            <?php echo $this->pageTitle($translate('Items'), 2); ?>
        <?php endif; ?>



        <?php echo $this->searchFilters(); ?>

        <div class="o-browse-controls">
            <?php echo $this->pagination(); ?>
            <?php // echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
            <?php echo $this->sortSelector($sortHeadings); ?>
        </div>



        <?php $this->trigger('view.browse.before'); ?>
        <ul class="o-resource-list f-grid-x f-grid-margin-x">
        <?php
        $headingTerm = $this->siteSetting('browse_heading_property_term');
        $bodyTerm = $this->siteSetting('browse_body_property_term');
        foreach ($items as $item):
            $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
            $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
        ?>
            <li class="o-item o-resource f-cell f-small-6 f-medium-4 f-large-3">
                <?php if ($itemThumbnail = $this->thumbnail($item, 'medium')): ?>
                <?php echo $item->linkRaw($itemThumbnail); ?>
                <?php endif; ?>
                <h4><?php echo $item->link($heading); ?></h4>
                <?php if ($body): ?>
                <div class="o-description"><?php echo $escape($body); ?></div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
        <?php echo ($itemSetShow) ? '</div>' : ''; ?>
        <?php $this->trigger('view.browse.after'); ?>
        <?php echo $this->pagination(); ?>

    </div>

</div>
