<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'o-item o-resource o-show');
$itemMedia = $item->media();
?>

<div class="f-grid-x f-grid-padding-x">

    <div class="f-cell f-small-12 f-medium-6">

        <?php echo $this->pageTitle($item->displayTitle(), 1); ?>

        <p class="t-lead"><?php echo $item->value('dcterms:description'); ?></p>

        <?php if (count($itemMedia) == 1): ?>
            <a class="f-button" href="<?php print($itemMedia[0]->originalUrl()); ?>">Download</a>
        <?php else: ?>
            TODO: Handle multiple media items.
        <?php endif; ?>

        <div class="f-callout">

            <h2><?php echo $translate('Item details'); ?></h2>

            <?php $this->trigger('view.show.before'); ?>

            <dl class="o-property-list o-item-property-list t-two-column-list">

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                        <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-subject-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Subject</dt>
                        <dd class="t-subject-property"><?php echo $item->value('dcterms:subject'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-type-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Type</dt>
                        <dd class="t-type-property"><?php echo $item->value('dcterms:type'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-format-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Format</dt>
                        <dd class="t-format-property"><?php echo $item->value('dcterms:format'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-language-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Language</dt>
                        <dd class="t-language-property"><?php echo $item->value('dcterms:language'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-coverage-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Coverage</dt>
                        <dd class="t-coverage-property"><?php echo $item->value('dcterms:coverage'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-creator-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Creator</dt>
                        <dd class="t-creator-property"><?php echo $item->value('dcterms:creator'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-rights-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Rights</dt>
                        <dd class="t-rights-property"><?php echo $item->value('dcterms:rights'); ?></dd>
                    </div>
                </div>

                <div class="t-dl-def f-card">
                    <div class="f-card-section">
                    <div class="f-float-right"><button type="button" class="f-button f-tiny f-hollow t-copy-button" data-clipboard-target=".t-contributor-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></div>
                        <dt>Contributor</dt>
                        <dd class="t-contributor-property"><?php echo $item->value('dcterms:contributor'); ?></dd>
                    </div>
                </div>

            </dl>

        </div>

        <div class="o-property">
            <?php $itemSets = $item->itemSets(); ?>
            <?php if (count($itemSets) > 0): ?>
            <h2><?php echo $translate('Item sets'); ?></h2>
            <?php foreach ($itemSets as $itemSet): ?>
            <div class="o-value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>

        <div class="o-property">
            <h2><?php echo $translate('Site pages'); ?></h2>
            <div class="o-values">
                <?php foreach ($sitePages as $sitePage): ?>
                <div class="o-value"><?php echo $sitePage->link($sitePage->title()); ?></div>
                <?php endforeach; ?>
            </div>
        </div>

        <?php endif; ?>

        <?php
            $page = $this->params()->fromQuery('page', 1);
            $property = $this->params()->fromQuery('property');
            $subjectValues = $item->displaySubjectValues($page, 25, $property);
        ?>

        <?php if ($subjectValues): ?>
        <div id="o-item-linked">
            <h2><?php echo $translate('Linked resources'); ?></h2>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>

    </div>

    <div class="f-cell f-small-12 f-medium-6">

        <?php if ($itemMedia[0]->mediaType() == 'application/pdf'): ?>

            <div class='t-item-preview t-document-item-preview'>
                <?php echo $this->thumbnail($item, 'large', ['alt' => 'An image of the item.']); ?>
            </div>

        <?php elseif ($itemMedia[0]->mediaType() == 'image/jpeg'): ?>

            <div class='t-item-preview t-image-item-preview'>

                <?php
                    // var_dump($itemMedia[0]->mediaData());
                    $itemMediaID = $itemMedia[0]->id();
                    $itemMediaOriginalDimensions = $itemMedia[0]->mediaData()['dimensions']['original'];
                    if ($itemMediaOriginalDimensions['height'] < $itemMediaOriginalDimensions['width']):
                        $itemMediaPreviewURL = 'https://edoid.danielflaum.net/iiif/' . $itemMediaID . '/square/^800,/0/default.jpg';
                ?>

                <span class="t-cropped-preview-notice">Cropped preview</span>
                <img src="<?php print($itemMediaPreviewURL); ?>" />

                <?php
                    else:
                        $itemMediaPreviewURL = 'https://edoid.danielflaum.net/iiif/' . $itemMediaID . '/full/^800,/0/default.jpg';
                ?>

                <img src="<?php print($itemMediaPreviewURL); ?>" />

                <?php endif; ?>

            </div>

        <?php elseif ($itemMedia[0]->mediaType() == 'audio/mpeg'): ?>

            <div class='t-item-preview t-sound-item-preview'>

                <?php
                    // echo json_encode($itemMedia[0]);
                    $itemMediaURL = $itemMedia[0]->originalUrl();
                ?>

                <audio>
                    <source src="<?php print($itemMediaURL) ?>">
                </audio>

            </div>

        <?php endif; ?>


    </div>

</div>

<?php if (count($itemMedia) > 1): ?>
<div class="o-media-list">
    <h2><?php echo $translate('Available media'); ?></h2>
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
