<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();
?>

<div class="grid-x grid-padding-x">

    <div class="cell small-12 medium-6">

        <?php echo $this->pageTitle($item->displayTitle(), 1); ?>

        <p class="lead"><?php echo $item->value('dcterms:description'); ?></p>

        <?php if (count($itemMedia) == 1): ?>
            <a class="button" href="<?php print($itemMedia[0]->originalUrl()); ?>">Download</a>
        <?php else: ?>
            TODO: Handle multiple media items.
        <?php endif; ?>

        <h2><?php echo $translate('Item details'); ?></h2>

        <?php $this->trigger('view.show.before'); ?>

        <dl class="property-list item-property-list t-two-column-list">

            <div class="dl-def">
                <dt>Subject <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".subject-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="subject-property"><?php echo $item->value('dcterms:subject'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Type <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".type-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="type-property"><?php echo $item->value('dcterms:type'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Format <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".format-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="format-property"><?php echo $item->value('dcterms:format'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Language <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".language-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="language-property"><?php echo $item->value('dcterms:language'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Coverage <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".coverage-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="coverage-property"><?php echo $item->value('dcterms:coverage'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Creator <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".creator-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="creator-property"><?php echo $item->value('dcterms:creator'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Rights <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".rights-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="rights-property"><?php echo $item->value('dcterms:rights'); ?></dd>
            </div>

            <div class="dl-def">
                <dt>Contributor <button type="button" class="button tiny hollow t-copy-button" data-clipboard-target=".contributor-property"><img src="<?php print($this->assetUrl('image/icon/clipboard-dark-violet.svg')); ?>" /> Copy</button></dt>
                <dd class="contributor-property"><?php echo $item->value('dcterms:contributor'); ?></dd>
            </div>

        </dl>

        <div class="property">
            <?php $itemSets = $item->itemSets(); ?>
            <?php if (count($itemSets) > 0): ?>
            <h2><?php echo $translate('Item sets'); ?></h2>
            <?php foreach ($itemSets as $itemSet): ?>
            <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>

        <div class="property">
            <h2><?php echo $translate('Site pages'); ?></h2>
            <div class="values">
                <?php foreach ($sitePages as $sitePage): ?>
                <div class="value"><?php echo $sitePage->link($sitePage->title()); ?></div>
                <?php endforeach; ?>
            </div>
        </div>

        <?php endif; ?>

        <?php
            $page = $this->params()->fromQuery('page', 1);
            $property = $this->params()->fromQuery('property');
            $subjectValues = $item->displaySubjectValues($page, 25, $property);
        ?>

        <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h2><?php echo $translate('Linked resources'); ?></h2>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>

    </div>

    <div class="cell small-12 medium-6">

        <?php if ($itemMedia[0]->mediaType() == 'application/pdf'): ?>

        <div class='item-preview document-item-preview'>
            <?php echo $this->thumbnail($item, 'large', ['alt' => 'An image of the item.']); ?>
        </div>

        <?php elseif ($itemMedia[0]->mediaType() == 'image/jpeg'): ?>

        <div class='item-preview image-item-preview'>

            <?php
                // var_dump($itemMedia[0]->id());
                $itemMediaID = $itemMedia[0]->id();
                $itemMediaOriginalDimensions = $itemMedia[0]->mediaData()['dimensions']['original'];
                if ($itemMediaOriginalDimensions['height'] < $itemMediaOriginalDimensions['width']):
                    $itemMediaPreviewURL = 'https://edoid.danielflaum.net/iiif/' . $itemMediaID . '/square/^800,/0/default.jpg';
            ?>

            <span class="t-cropped-preview-notice">Cropped preview</span>
            <img src="<?php print($itemMediaPreviewURL); ?>" />

            <?php
                else:
                    $itemMediaPreviewURL = 'https://edoid.danielflaum.net/iiif/' . $itemMediaID . '/full/^800,/0/default.jpg';
            ?>

            <img src="<?php print($itemMediaPreviewURL); ?>" />

            <?php endif; ?>

        </div>

        <?php endif; ?>

    </div>

</div>

<?php if (count($itemMedia) > 1): ?>
<div class="media-list">
    <h2><?php echo $translate('Available media'); ?></h2>
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
