<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>

<?php echo $this->doctype(); ?>

<?php echo $this->htmlElement('html'); ?>

    <head>

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink(); ?>

        <?php echo $this->headStyle(); ?>

        <?php echo $this->headScript(); ?>

    </head>



    <?php echo $this->htmlElement('body'); ?>

        <a id="skipnav" class="show-for-sr" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>

        <?php echo $userBar; ?>

        <header>

            <div class="top-bar grid-container">

                <div class="top-bar-left">

                    <img src="<?php echo $this->assetUrl('image/logo-dark-background.svg'); ?>">

                </div>

                <div class="top-bar-right">

                    <div id="search">
                        <?php echo $this->partial('common/search-form'); ?>
                    </div>

                </div>

            </div>

        </header>



        <div class="grid-container">

            <div class="grid-x grid-padding-x">

                <!-- <div class="cell show-for-medium medium-3">

                    <nav>

                        <?php
                        // echo $site->publicNav()->menu()->renderMenu(null, [
                        //     'maxDepth' => $this->themeSetting('nav_depth') - 1
                        // ]);
                        ?>

                    </nav>

                </div> -->

                <div id="content" role="main" class="cell small-12">

                    <?php echo $this->content; ?>

                </div>

                <div class="cell small-12">

                    <footer>

                        <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                        <?php endif; ?>

                    </footer>

                </div>

            </div>

        </div>

        <script type="text/javascript" src="<?php print($this->assetUrl('js/clipboard.js')); ?>"></script>
        <script type="text/javascript" src="<?php print($this->assetUrl('js/default.js')); ?>"></script>

    </body>

</html>
