<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }

            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>

        <a id="skipnav" class="show-for-sr" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>

        <?php echo $userBar; ?>

        <header>

            <div class="top-bar">

                <div class="top-bar-left">

                    <ul class="menu">

                        <li>
                            <a href="<?php echo $site->url(); ?>" class="site-title">
                            <?php if ($this->themeSetting('logo')): ?>
                                <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                            <?php else: ?>
                                <?php echo $escape($siteTitle); ?>
                            <?php endif; ?>
                            </a>
                        </li>

                    </ul>

                </div>

                <div class="top-bar-right">

                    <div id="search">
                        <?php echo $this->partial('common/search-form'); ?>
                    </div>

                </div>

            </div>

        </header>

        <div class="grid-x grid-padding-x">

            <div class="cell show-for-medium medium-3">

                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>

            </div>

            <div id="content" role="main" class="cell small-12 medium-9">

                <?php echo $this->content; ?>

            </div>

            <div class="cell small-12">

                <footer>
                    <?php if ($footerContent = $this->themeSetting('footer')): ?>
                    <?php echo $footerContent; ?>
                    <?php else: ?>
                        <?php echo $this->translate('Powered by Omeka S'); ?>
                    <?php endif; ?>
                </footer>

            </div>

        </div>

    </body>

</html>
